### ISSUE TITLE
Howto compile rm2pdf

### ISSUE THREAD

**Issue by qwert2003** [poundifdef/go-remarkable2pdf#1]
Reading the README.md I miss a description how to compile a binary file `rm2pdf`.
It would be helpful for people without golang experience to have some guidance.

Your project could be a useful tool for testing rm files (e.g. generated by [drawj2d](https://sourceforge.net/p/drawj2d/wiki/reMarkable/)) without the need to upload to the device.

**Comment by ddvk** [comment]
so i would like to try different implementations, and made a simple cmdline tool using this project [rm-convert](https://github.com/ddvk/rm-convert)

you just clone and run `make` or use the binary from release

**Comment by poundifdef** [comment]
Thanks for this! I hadn't even thought to create a main function so that it could be used standalone. Thank you @ddvk for sharing. Interested to see the results you've had with other conversion libraries.
